version: '3.5'
services:
  crawler:
    image: spotify-crawler
    container_name: spotify-crawler
    hostname: "spotify-crawler"
    env_file: ./config/crawler.env
    volumes:
      - ./crawler/app:/usr/local/src/app
    entrypoint:
      - python
      - ./app.py
      - acetones
  crawler-tests:
    image: spotify-crawler
    container_name: spotify-crawler-tests
    volumes:
      - ./crawler/app:/usr/local/src/app
    entrypoint:
      - python
      - -m
      - unittest
      - discover
