version: '3.3'
services:
  crawler:
    image: spotify-crawler
    container_name: spotify-crawler
    hostname: "spotify-crawler"
    env_file: ./config/.env.crawler
    volumes:
      - ./crawler/app:/usr/local/src/app
    entrypoint:
      - python
      - ./app.py
      - acetones
  test-crawler:
    image: spotify-crawler
    container_name: spotify-crawler-tests
    volumes:
      - ./crawler/app:/usr/local/src/app
    entrypoint:
      - python
      - -m
      - unittest
      - discover
  feature-extractor:
    image: feature-extractor
    container_name: feature-extractor
    env_file: ./config/.env.extractor
