version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - setup_remote_docker
      - run: touch config/.env.crawler config/.env.extractor
      - run: make build-all
      - run: make test-all
      - run: make style-all
