version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - setup_remote_docker
      - run: touch config/.env.crawler config/.env.extractor
      - run:
          command: |
            sudo pip install pipenv
            cat api/requirements.txt | xargs pipenv install
      - run: make ci
      - persist_to_workspace:
          root: .
          paths:
            - docker-image
  deploy:
    docker:
      - image: circleci/python:3.7.2
        environment:
          AWS_DEFAULT_OUTPUT: json
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: workspace
      - run: make push-extractor
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
